### ISSUE TITLE
Where can I download the provided dataset?

### ISSUE THREAD

**Issue by MaxChanger** [gmum/points2nerf#1]
Thanks for the good work!
As the title, I want to know where can I download the provided dataset without the need for complex preprocessing?
> Or download provided data: ShapeNet cars, planes, chairs with 50 renders, each 200x200 on 2048 colored points.

**Comment by Ideefixze** [comment]
Hi, 
I put the link for download in the README.

**Comment by MaxChanger** [comment]
ok, thank you very much ~ @Ideefixze
